### ISSUE TITLE
Add testId to interactive island-ui components

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#254]
Our shared components need props to help with automated testing.

Interactive components should support a prop called `testId`, which is forwarded to `data-testId` on the primary interactive element in the DOM. This kind of attribute works well with Cypress and `testing-library`.

If a component has sub-components, it can use its `testId` as a prefix for those components, eg:

```
const Calendar = ({ testId = &#39;calendar, ...stuff }) =>
  <>
    ...
    <Button testId={`${testId}.nextMonth`} />
  </>
```

**Comment by oddsson** [comment]
According to https://testing-library.com/docs/guide-which-query/, other queries should be used before using `getByTestId`. I'd argue that instead of placing test-id's on interactive elements to query by, people should query by `getByRole("Button", {name: "Accessible button text"})` like described here 👉  https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-the-wrong-query

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
