### ISSUE TITLE
Failure to retrieve Pósthólf in download-service does not result in HTTP error code

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#4452]
Example URL: https://api.island.is/download/v1/electronic-documents/xxxxxx

**Comment by osk** [comment]
For certain files, requesting them for download results in a timeout of 30s to be hit. This is not always 
A file is shown, but it's not a legit PDF. Downloading and open reveals (in some instances?)
`{"statusCode":404,"message":"Cannot GET /download/v1/electronic-documents/<GUID>","error":"Not Found"}`
Testing this on "gamlar mínar síður" (minarsidur.island.is) results in the document being rendered *after about 45 seconds*.

Previously the timeout was raised from 10s to 30s, but this specific document provider can be very slow, so a better tactic is required.

Plan:

1. Talk with owners of document service ("Pósthólf") and ask about slowness and historical data about that and ways to perhaps mitigate?
2. Look into increasing timeout to even more, what's a reasonable upper limit?
3. For errors, the current handling of showing an "empty" (but really a broken) PDF is bad for UX, how can we do better?
4. Improve error logging, due to the 30s timeout the request is long gone from context when debugging, adding documentId to logged info?

**Comment by osk** [comment]
Is the quick fix while we figure out a permanent solution to increase the timeout to 60s? 🙈

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
