### ISSUE TITLE
(Redis) ClusterAllFailedError: Failed to refresh slots cache.

### ISSUE THREAD

**Issue by busla** [island-is/island.is#4588]
We have been getting this error a few times a day now, mostly on `web-gjafakort-api` but also on `web-application-system-api`.

I can confirm that there is sudden burst of CACHE MISS and therefore another burst of new connections right after.

The `slotsRefreshTimeout` is set to 2 seconds but `slotsRefreshInterval` is _not_ set so it defaults to 5 seconds.
https://github.com/island-is/island.is/blob/main/libs/cache/src/lib/cache.ts#L55

Might be worth considering creating a larger time gap between the timeout and the refreshInterval.

Reference:
https://github.com/luin/ioredis/issues/711#issuecomment-841213698
https://github.com/luin/ioredis/blob/HEAD/API.md#new-clusterstartupnodes-options

**Comment by jeremytm** [comment]
In an otherwise healthy cluster, we typically see this during a large scale event where:
- hundreds of AWS lambda functions spin up at the same time (almost 1000 in some cases)
- each lambda client typically creates more than one connection to redis
- each lambda client reads and writes data to redis, creating a lot of data evictions with `maxmemory-policy: allkeys-lfu`

Related info points
- `maxclients: 46000` with elasticache, while Current Connections peaks at 5,749 so plenty of room for new connections
- CPU Utilization `max` cloudwatch stats peaked at 48.1%, so we are **not** CPU bound

I've been unable to confirm it from my research, but even though we are well under max connections and we're not CPU bound the link I am drawing is that when the server is evicting a lot of data, it also has trouble assigning new connections. 

There doesn't seem to be a good reason for this, given there's plenty of room in terms of CPU, so there must be some delay in data eviction (memory IO?) to make room for new data, while also trying add new connections in an event loop where those connections must wait on eviction events. Correct me if I'm wrong!

Possible solutions:
- upgrade the instance to provide more memory so that we're not relying on a maxmemory policy in general
- increase `slotsRefreshTimeout` to an amount of time large enough to handle typical delays due to evictions
- (For us since we use redis as a cache on top of DynamoDB) Disable redis caching for these large scale events, and load data direct from Dynamo, and don't bother writing read data to cache (only update cache if source data writes are needed)

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
