### ISSUE TITLE
ui-core's Link component imports next/Link

### ISSUE THREAD

**Issue by maranomynet** [island-is/island.is#4680]
...which seems kind of suspect, no?

https://github.com/island-is/island.is/blob/2bd49d8902837115799a02b0fb46be1cb002eb5b/libs/island-ui/core/src/lib/Link/Link.tsx#L2

**Comment by jeremybarbet** [comment]
We are using the UI library in both Next.js and CRA apps, meaning returning a Nextjs component into CRA is definitely not gonna work.

It would be better to extract the router logic into another component, e.g. `NextLinkWrapper`/`CRALinkWrapper` and import their specific types and components there.

The issue didn't raise before, because both projects using CRA (application-system-form and service-portal) are not importing the Link component from the UI library

**Comment by maranomynet** [comment]
The CRA projects probably tried importing it and then found it didn't work and went 🤷 and did their own thing.

**Comment by miamiultras** [comment]
Hey @maranomynet @jeremybarbet
we faced similar issue in our project and solution we did is to specify what type of link we want while creating Link element in specific project/module:
```
<Link as={RouterLink} href="/">
<Link as={NextLink} href="/">
```
Maybe something similar could be implemented here to avoid importing next/Link in places where it's actually not used and can cause some issues. Let me know what u think or if u need more details.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
