### ISSUE TITLE
Address warning: (node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#4959]
Use more targeted TLS settings (with soffia API if I recall correctly)

**Comment by pshomov** [comment]
@dabbeg In general I am trying to get rid of the noise in DD coming from restarting this service.

**Comment by dabbeg** [comment]
@pshomov I am wondering if we should try to import the self signed certificate into the service and use something like this node option: [https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file).
Instead of disabling the validation of certificates as we are doing now.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
