### ISSUE TITLE
Feature request: Add WebAuthn standard for login into island.is

### ISSUE THREAD

**Issue by gunnarif** [island-is/island.is#5190]
Add WebAuthn standard as a way to login to Ísland.is.
This will allow FIDO security keys like YubiKey, log in with fingerprints, window hello and many more very secure methods.

Try out and read about WebAuthn at https://webauthn.io/

**Comment by gunnarif** [comment]
To clarify. 
You onboard the key after you do a normal login with auðkenni.
You can then use the key to allow longer sessions, when that session times out you still have to use auðkenni.

@eirikurn

**Comment by eirikurn** [comment]
cc @hrefnalind 

This is an interesting suggestion to provide better UX in our identity server.

If the user opts in, then we could "remember" the user for 30-60 days, and when the user comes back they only have to use FaceID, TouchID or some other secure authentications, instead of full electronic ID.

Though this would be a fairly big task and we'd need to consider how this could fit into the trust framework.

**Comment by Gunni** [comment]
@eirikurn I do not agree with what you describe.

A user logs in normally using auðkenni and gets in, he then adds a WebAuthN credential to his account. From that point onwards he can log in using username password and 2fa credential (f.ex by touching his security key, or by providing fingerprint to it or similar).

After a user establishes this kind of secure credential, talking to auðkenni at all is redundant.

You can even go further and let the user add a [Discoverable Credential](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html) and the login process for the user becomes: Click sign in with security key, provide FIDO2 pin or similar challenge, and then touch the security key.

All of the above is unphishable due to how the protocol is designed.

**Comment by hrefnalind** [comment]
Thank you for the feature request and your suggestion. We will review this solution and see if it fits island.is the authentication system.

**Comment by hrefnalind** [comment]
@gunnarif or @Gunni do you know of any service provider that is using the standard ?

**Comment by Gunni** [comment]
> @gunnarif or @Gunni do you know of any service provider that is using the standard ?

[Support in browsers](https://caniuse.com/?search=webauthn)

The big ones would be
- [Microsoft](https://support.microsoft.com/en-us/windows/sign-in-to-your-microsoft-account-with-windows-hello-or-a-security-key-800a8c01-6b61-49f5-0660-c2159bea4d84)
- [Google](https://www.google.com/landing/2step/) (also has a [security key ONLY method](https://landing.google.com/advancedprotection/), without insecure fallback)
- [Facebook](https://www.facebook.com/help/401566786855239)
- [GitHub](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-security-key)
- [DropBox](https://help.dropbox.com/teams-admins/team-member/enable-two-step-verification#securitykey)

And many, many others.

Note that WebAuthN is not a service, it is a protocol that you implement on your web service and users can use it if they have the security keys that implement it. So no service fees, no contracts, no worrying about service provider outages, etc...

**Comment by sporri** [comment]
Getum við gert upvote? FIDO2 væri mikil dásemd að fá

**Comment by Gunni** [comment]
> Getum við gert upvote? FIDO2 væri mikil dásemd að fá

![image](https://user-images.githubusercontent.com/358099/144712339-3eb02ae4-6d95-4d9a-ac43-1d96a147d400.png)

Notar þennan takka til að upvota.

**Comment by eirikurn** [comment]
> @eirikurn I do not agree with what you describe.
> 
> A user logs in normally using auðkenni and gets in, he then adds a WebAuthN credential to his account. From that point onwards he can log in using username password and 2fa credential (f.ex by touching his security key, or by providing fingerprint to it or similar).
> 
> After a user establishes this kind of secure credential, talking to auðkenni at all is redundant.
> 
> You can even go further and let the user add a [Discoverable Credential](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html) and the login process for the user becomes: Click sign in with security key, provide FIDO2 pin or similar challenge, and then touch the security key.
> 
> All of the above is unphishable due to how the protocol is designed.

I think we're basically talking about the same thing.

Couple of notes:

* We're generally moving away from Íslykill, so we don't have a "Username/Password" flow to add FIDO2 as a 2fa credential. We only have Electonic ID in the new login system, where you username is your (public) phone number and national ID. If we were to adopt FIDO2, we would go straight for something like Discoverable Credentials.
* The flow you describe is similar to how the upcoming Island.is App will work. There you perform electronic ID once, then you can use device auth to get into the app from then on. 
* The SPs you listed are huge, but some of our SPs are way more paranoid than them, even more than online banks. Heilsuvera for example does not even support two factor Íslykill and instead requires Electronic ID for all authentications.
* There is a general POV in gov that Electronic IDs are the only/most secure form of true digital authentication, since it is linked to you (through a SIM/app on your phone) and the only way to get it is through physical authentication (eg in a bank). All other methods of digital authentication get compared to that "gold standard", and are generally trusted less since they are easier to "share".
* In the Island.is app, I think we'll require a "full" electronic ID authentication periodically to make sure you are who you are, and not someone who somehow authenticated with your electronic ID once. This is why I suggested using FIDO2 to support similar functionality on the web; eg "remember the user for 30-60 days".
* FIDO2 may complicate the trust-system of the IDP for our local SPs on one hand as well as European SP through [eIDAS](https://en.wikipedia.org/wiki/EIDAS). It would open up a whole world of "authentication options", where we're basically putting our trust in the user's setup/hardware. The authentication could theoretically be anything from an insecure browser extension to a hardware based DNA check.
* For our own SPs, we could list Webauthn as a supported authentication method so the SPs can decide for themselves if they want to support it. However, the eIDAS certification process is so convoluted that I'm not sure if we could support FIDO2 for those SPs except with a fairly low trust rating.

**Comment by Gunni** [comment]
The big problem with credentials that are non-local to the device you are browsing on, is that you can be fooled into accepting the challenge on a fake domain, and therefore authenticating an attacker...

A demonstration I saw on a [Facebook post](https://www.facebook.com/groups/758283317569443/posts/6884410724956641/) discussing this
![391611346_10230416803794881_3865968740366079186_n](https://github.com/island-is/island.is/assets/358099/4d2679ef-8c34-4eb9-83f4-cce7329a3fbb)

With FIDO2 you the user is UNABLE TO accept such a challenge, because the challenge will not succeed because the domain is incorrect.

Popping up a number and saying don't accept unless this unless the number matches is pointless, because:
1. The user doesn't need to enter it
2. Even if they had to enter it, the attacker controlled website could just show the number being requested by the real origin

FIDO2 prevents all of that by:
1. Working with the browser
2. Validating that the domain the browser is on is correct

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"

**Comment by Gunni** [comment]
I'd like this to be reconsidered. Account takeovers are getting more common.

**Comment by Gunni** [comment]
PDF: [FIDO Alliance White Paper: Using FIDO with eIDAS Services](https://fidoalliance.org/wp-content/uploads/2020/04/FIDO-deploying-FIDO2-eIDAS-QTSPs-eID-schemes-white-paper.pdf)

> # Conclusions
> To summarize, FIDO2 provides an easy-to-use and secured alternative to other potentially phishable solutions.
>  The FIDO2 standard is suitable as the authentication mechanism for substantial or high assurance levels for both eID schemes and for
authentication to a remote signing QTSP, as defined in the eIDAS regulation

How is this @eirikurn?

**Comment by Gunni** [comment]
How about this, enroll the FIDO2 credential during in-person handoff, and don't allow user enrollment of FIDO2 credentials?

That way you control what devices are used?

I mean you [can already control](https://developers.yubico.com/WebAuthn/Concepts/Securing_WebAuthn_with_Attestation.html) that server side too but still.

**Comment by Gunni** [comment]
[Austrian government adds YubiKeys to its electronic ID system](https://www.yubico.com/blog/austrian-government-adds-yubikey-support-to-its-national-electronic-identification-system/).

We are falling behind.
