### ISSUE TITLE
Add RNG to Cypress job dispatcher

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#7358]
There is a bug when cypress (re)runs failed jobs. At a certain point it stops accepting new tests into the suit, and when you rerun the job, it tries to add more tests because you're technically using the old cypress run. 
Stupid... yeah... 
We did add some additional unique factors to this, but it didn't work for these particular jobs. 

Enter RNG. 
Got to append a randomized string to the end of the cypress job creation. Should solve the issue once and for all. 

https://islandis.slack.com/archives/C019LNRM6LE/p1652129217966799

**Comment by peturgq** [comment]
I looked into this a bit,
Problem seems to be that we are setting the build_id in the prepare phase, there a random UUID is applied:
`$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT-$(uuidgen)`

Then the output is picked up later in the E2E test:
```  e2e:
    needs:
      - prepare
    env:
      E2E_BUILD_ID: ${{needs.prepare.outputs.E2E_BUILD_ID}}
```
So the BUILD_ID var is generated once per prepare, there are a couple of ways to approach this and I'm not sure which would be best because I don't know where the tentacles lie:

1. By setting some kind of forced rebuild of prepare for the target when a failed job is re-run.

2. Append $GITHUB_RUN_ATTEMPT to E2E_BUILD_ID also inside specific builds.

3. Random string or uuid inside e2e-ci.js for CMD
